// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ChangelogPostDocumentDataSlicesSlice = never;

/**
 * Content for Changelog Post documents
 */
interface ChangelogPostDocumentData {
  /**
   * Fecha Del Changelog field in *Changelog Post*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: changelog_post.fecha_del_changelog
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  fecha_del_changelog: prismic.TimestampField;

  /**
   * Título del Changelog field in *Changelog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: changelog_post.titulo_del_changelog
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_del_changelog: prismic.KeyTextField;

  /**
   * Modulo field in *Changelog Post*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Dashboard
   * - **API ID Path**: changelog_post.modulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  modulo: prismic.SelectField<
    "Dashboard" | "Planificaciones" | "Enfermería",
    "filled"
  >;

  /**
   * Resumen de Cambios field in *Changelog Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: changelog_post.resumen_de_cambios
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  resumen_de_cambios: prismic.RichTextField;

  /**
   * Slice Zone field in *Changelog Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: changelog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ChangelogPostDocumentDataSlicesSlice> /**
   * Meta Title field in *Changelog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: changelog_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Changelog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: changelog_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Changelog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: changelog_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Changelog Post document from Prismic
 *
 * - **API ID**: `changelog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ChangelogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ChangelogPostDocumentData>,
    "changelog_post",
    Lang
  >;

export type AllDocumentTypes = ChangelogPostDocument;

/**
 * Default variation for ChangelogPost Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ChangelogPostSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ChangelogPost*
 */
type ChangelogPostSliceVariation = ChangelogPostSliceDefault;

/**
 * ChangelogPost Shared Slice
 *
 * - **API ID**: `changelog_post`
 * - **Description**: ChangelogPost
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ChangelogPostSlice = prismic.SharedSlice<
  "changelog_post",
  ChangelogPostSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ChangelogPostDocument,
      ChangelogPostDocumentData,
      ChangelogPostDocumentDataSlicesSlice,
      AllDocumentTypes,
      ChangelogPostSlice,
      ChangelogPostSliceVariation,
      ChangelogPostSliceDefault,
    };
  }
}
