export * from "../Enfermeria/registro_atencion"
export * from "../Enfermeria/lugar"
export * from "../Enfermeria/motivo"
export * from "../Enfermeria/tratamiento"
export * from "../Enfermeria/enfermedad_discapacidad"
export * from "../Enfermeria/ocupacion"
export * from "../Enfermeria/tipo_accidente"
export * from "../Enfermeria/tipo_actividad"