export * from './curso'
export * from './curso_asignatura'
export * from './establecimiento'
export * from './grados_sige'
export * from './periodo_escolar'
export * from './especialidad'
export * from './asignatura_curricular'
export * from './asignatura_sige'