export * from "../Matricula/antecedente_familiar";
export * from "../Matricula/antecedente_personal";
export * from "../Matricula/antecedente_salud";
export * from "../Matricula/autorizado_retiro";
export * from "../Matricula/condicion_matricula";
export * from "../Matricula/estado_matricula";
export * from "../Matricula/matricula";
export * from "../Matricula/tipo_matricula";
export * from "../Matricula/tutor_economico";
