// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
    changelog_post: defineAsyncComponent(
        () => import("./ChangelogPost/index.vue"),
    ),
});
