export * from './Establecimiento';
export * from './Planificacion';
export * from './Curriculum';
export * from './Matricula';
export * from './LibroDigital';
export * from './General';
export * from './Health';
export * from './Auth';
export * from './Comunicacion';
export * from './Enfermeria';
export * from './Evaluacion'
