name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npx npm@latest install

      - name: Build
        run: npm run prepack

      - name: Update Version
        run: |
          git config --local user.email "josepuma@sayrin.cl"
          git config --local user.name "Jose Puma"
          VERSION=$(echo ${{ github.event.release.tag_name }} | sed 's/v//')
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/g" package.json
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Bump version to $VERSION"
            git push
          else
            echo "No changes to commit"
            exit 0
          fi

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_REDCOLLEGE_ACCESS }}
