name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npx nypm@latest i

      - name: Build
        run: npm run prepack

      - name: Update Version
        run: |
          git config --local user.email "josepuma@sayrin.cl"
          git config --local user.name "Jose Puma"
          VERSION=$(echo ${{ github.event.release.tag_name }} | sed 's/v//')
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/g" package.json
          if [ "$(git status --porcelain)" = "" ]; then
            echo "No changes to commit"
            exit 0
          fi
          git add .
          git commit -m "Bump version to $VERSION"

      - name: npm publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_NPM_TOKEN_REDCOLLEGE_UI }}

