name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npx nypm@latest i

      - name: Build
        run: npm run prepack

      - name: Bump version & push
        run: |
          git config --global user.name 'Automated publish'
          git config --global user.email 'josepuma@sayrin.cl'
          npm version patch
          git push && git push --tags

      - name: npm publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_NPM_TOKEN_REDCOLLEGE_UI }}

