name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npx npm@latest install

      - name: Build
        run: npm run dev:prepare

      - name: Build
        run: npm run prepack

      - name: Update Version
        run: |
            git config --local user.email "josepuma@sayrin.cl"
            git config --local user.name "Jose Puma"
            git add .
            git commit -m "Commit changes before version bump" || echo "No changes to commit"
            npm version patch
            git push && git push --tags

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_REDCOLLEGE_ACCESS }}
