name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check-author:
    runs-on: ubuntu-latest
    outputs:
      is-authorized: ${{ steps.check.outputs.is-authorized }}
    steps:
      - name: Check commit author
        id: check
        run: |
          AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae')
          if [[ "$AUTHOR_EMAIL" == "josepuma@sayrin.cl" || "$AUTHOR_EMAIL" == "marcosdguilarte74@gmail.com" ]]; then
            echo "is-authorized=true" >> $GITHUB_OUTPUT
          else
            echo "is-authorized=false" >> $GITHUB_OUTPUT
          fi

  build:
    runs-on: ubuntu-latest
    needs: check-author
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npx npm@latest install
      - name: Build
        run: npm run dev:prepare
      - name: Build
        run: npm run prepack

  publish-package:
    runs-on: ubuntu-latest
    needs: [check-author, build]
    if: |
      github.event_name == 'push' && 
      github.ref == 'refs/heads/main' && 
      needs.check-author.outputs.is-authorized == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npx npm@latest install
      - name: Build
        run: npm run dev:prepare
      - name: Build
        run: npm run prepack
      - name: Update Version
        run: |
            git config --local user.email "josepuma@sayrin.cl"
            git config --local user.name "Jose Puma"
            git add .
            git commit -m "Commit changes before version bump" || echo "No changes to commit"
            npm version patch
            git push && git push --tags
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_REDCOLLEGE_ACCESS }}
